import cv2
image=cv2.imread('sample.jpg')
resized_image = cv2.resize(image, (800, 600))
cv2.imshow("original image", image)
rotated_image =cv2.rotate(resized_image, cv2.ROTATE_90_CLOCKWISE)
flipped_image = cv2.flip(resized_image, -1)
cropped_image = resized_image[100:400, 200:600]
cv2.imshow("cropped image", cropped_image)
cv2.imshow("flipped image", flipped_image)
cv2.imshow("rotated image", rotated_image)
grayscale_image = cv2.cvtColor(resized_image, cv2.COLOR_BGR2GRAY)
hsv= cv2.cvtColor(resized_image, cv2.COLOR_BGR2HSV)
lv=cv2.cvtColor(resized_image, cv2.COLOR_BGR2HLS)
cv2.imshow("HLS image", lv)
cv2.imshow("HSV image", hsv)
cv2.imshow("grayscale image", grayscale_image)
cv2.imshow("resized image", resized_image)
cv2.waitKey(0)
cv2.destroyAllWindows()
